trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    # Ensure server is started first for tests to run
    npm run start &
    npm run test
  displayName: 'npm install and test'
